
// This file was generated by Yuri, a type-safe URI builder for Kotlin.
package main.kotlin

import main.kotlin.G.*

abstract class GFile<T>( path: String ) {
  open val path: String = "$path/${javaClass.simpleName}"
  override fun toString() = path
}

open class G private constructor() {
  open class project_ {

@JvmName("_dot_") operator fun div(a: _dot_.Companion) = _dot_<project_>("/")

@JvmName("out") operator fun div(a: out.Companion) = out<project_>("/")

@JvmName("settings_dot_gradle") operator fun div(a: settings_dot_gradle.Companion) = settings_dot_gradle<project_>("/")

@JvmName("build") operator fun div(a: build.Companion) = build<project_>("/")

@JvmName("build_dot_gradle_dot_kts") operator fun div(a: build_dot_gradle_dot_kts.Companion) = build_dot_gradle_dot_kts<project_>("/")

@JvmName("_dot_gradle") operator fun div(a: _dot_gradle.Companion) = _dot_gradle<project_>("/")

@JvmName("README_dot_md") operator fun div(a: README_dot_md.Companion) = README_dot_md<project_>("/")

@JvmName("gradlew_dot_bat") operator fun div(a: gradlew_dot_bat.Companion) = gradlew_dot_bat<project_>("/")

@JvmName("src") operator fun div(a: src.Companion) = src<project_>("/")

@JvmName("_dot_idea") operator fun div(a: _dot_idea.Companion) = _dot_idea<project_>("/")

@JvmName("gradlew") operator fun div(a: gradlew.Companion) = gradlew<project_>("/")

@JvmName("gradle") operator fun div(a: gradle.Companion) = gradle<project_>("/")

    companion object: project_()
  }


open class _dot_<T>(path: String): GFile<T>(path) { companion object }

open class `out`<T>(path: String): GFile<T>(path) { companion object }

open class production<T>(path: String): GFile<T>(path) { companion object }

open class classes<T>(path: String): GFile<T>(path) { companion object }

open class settings_dot_gradle<T>(path: String): GFile<T>(path) { companion object }

open class build<T>(path: String): GFile<T>(path) { companion object }

open class generated<T>(path: String): GFile<T>(path) { companion object }

open class source<T>(path: String): GFile<T>(path) { companion object }

open class java<T>(path: String): GFile<T>(path) { companion object }

open class kotlin<T>(path: String): GFile<T>(path) { companion object }

open class resources<T>(path: String): GFile<T>(path) { companion object }

open class main<T>(path: String): GFile<T>(path) { companion object }

open class sessions<T>(path: String): GFile<T>(path) { companion object }

open class compileKotlin<T>(path: String): GFile<T>(path) { companion object }

open class tmp<T>(path: String): GFile<T>(path) { companion object }

open class compileJava<T>(path: String): GFile<T>(path) { companion object }

open class pluginDescriptors<T>(path: String): GFile<T>(path) { companion object }

open class co_dot_ndan_dot_yuri_dot_properties<T>(path: String): GFile<T>(path) { companion object }

open class build_dot_gradle_dot_kts<T>(path: String): GFile<T>(path) { companion object }

open class _dot_gradle<T>(path: String): GFile<T>(path) { companion object }

open class buildOutputCleanup<T>(path: String): GFile<T>(path) { companion object }

open class outputFiles_dot_bin<T>(path: String): GFile<T>(path) { companion object }

open class cache_dot_properties<T>(path: String): GFile<T>(path) { companion object }

open class buildOutputCleanup_dot_lock<T>(path: String): GFile<T>(path) { companion object }

open class vcsWorkingDirs<T>(path: String): GFile<T>(path) { companion object }

open class gc_dot_properties<T>(path: String): GFile<T>(path) { companion object }

open class README_dot_md<T>(path: String): GFile<T>(path) { companion object }

open class gradlew_dot_bat<T>(path: String): GFile<T>(path) { companion object }

open class src<T>(path: String): GFile<T>(path) { companion object }

open class test<T>(path: String): GFile<T>(path) { companion object }

open class _dot_idea<T>(path: String): GFile<T>(path) { companion object }

open class workspace_dot_xml<T>(path: String): GFile<T>(path) { companion object }

open class gradle_dot_xml<T>(path: String): GFile<T>(path) { companion object }

open class kotlinc_dot_xml<T>(path: String): GFile<T>(path) { companion object }

open class vcs_dot_xml<T>(path: String): GFile<T>(path) { companion object }

open class markdown_dash_navigator<T>(path: String): GFile<T>(path) { companion object }

open class profiles_settings_dot_xml<T>(path: String): GFile<T>(path) { companion object }

open class markdown_dash_navigator_dot_xml<T>(path: String): GFile<T>(path) { companion object }

open class modules<T>(path: String): GFile<T>(path) { companion object }

open class yuri_test_dot_iml<T>(path: String): GFile<T>(path) { companion object }

open class yuri_main_dot_iml<T>(path: String): GFile<T>(path) { companion object }

open class kotlinScripting_dot_xml<T>(path: String): GFile<T>(path) { companion object }

open class misc_dot_xml<T>(path: String): GFile<T>(path) { companion object }

open class uiDesigner_dot_xml<T>(path: String): GFile<T>(path) { companion object }

open class gradlew<T>(path: String): GFile<T>(path) { companion object }

open class gradle<T>(path: String): GFile<T>(path) { companion object }

open class wrapper<T>(path: String): GFile<T>(path) { companion object }

open class gradle_dash_wrapper_dot_properties<T>(path: String): GFile<T>(path) { companion object }

open class gradle_dash_wrapper_dot_jar<T>(path: String): GFile<T>(path) { companion object }

  companion object {
    fun uri(path: Any) = println(path)
  }
}
@JvmName("2") operator fun `out`<project_>.div(a: production.Companion) = production<`out`<project_>>(path)
@JvmName("3") operator fun production<`out`<project_>>.div(a: classes.Companion) = classes<production<`out`<project_>>>(path)
@JvmName("4") operator fun build<project_>.div(a: generated.Companion) = generated<build<project_>>(path)
@JvmName("5") operator fun generated<build<project_>>.div(a: source.Companion) = source<generated<build<project_>>>(path)
@JvmName("6") operator fun build<project_>.div(a: classes.Companion) = classes<build<project_>>(path)
@JvmName("7") operator fun classes<build<project_>>.div(a: java.Companion) = java<classes<build<project_>>>(path)
@JvmName("8") operator fun classes<build<project_>>.div(a: kotlin.Companion) = kotlin<classes<build<project_>>>(path)
@JvmName("9") operator fun build<project_>.div(a: resources.Companion) = resources<build<project_>>(path)
@JvmName("10") operator fun resources<build<project_>>.div(a: main.Companion) = main<resources<build<project_>>>(path)
@JvmName("11") operator fun build<project_>.div(a: kotlin.Companion) = kotlin<build<project_>>(path)
@JvmName("12") operator fun kotlin<build<project_>>.div(a: sessions.Companion) = sessions<kotlin<build<project_>>>(path)
@JvmName("13") operator fun kotlin<build<project_>>.div(a: compileKotlin.Companion) = compileKotlin<kotlin<build<project_>>>(path)
@JvmName("14") operator fun build<project_>.div(a: tmp.Companion) = tmp<build<project_>>(path)
@JvmName("15") operator fun tmp<build<project_>>.div(a: compileJava.Companion) = compileJava<tmp<build<project_>>>(path)
@JvmName("16") operator fun build<project_>.div(a: pluginDescriptors.Companion) = pluginDescriptors<build<project_>>(path)
@JvmName("17") operator fun pluginDescriptors<build<project_>>.div(a: co_dot_ndan_dot_yuri_dot_properties.Companion) = co_dot_ndan_dot_yuri_dot_properties<pluginDescriptors<build<project_>>>(path)
@JvmName("18") operator fun _dot_gradle<project_>.div(a: buildOutputCleanup.Companion) = buildOutputCleanup<_dot_gradle<project_>>(path)
@JvmName("19") operator fun buildOutputCleanup<_dot_gradle<project_>>.div(a: outputFiles_dot_bin.Companion) = outputFiles_dot_bin<buildOutputCleanup<_dot_gradle<project_>>>(path)
@JvmName("20") operator fun buildOutputCleanup<_dot_gradle<project_>>.div(a: cache_dot_properties.Companion) = cache_dot_properties<buildOutputCleanup<_dot_gradle<project_>>>(path)
@JvmName("21") operator fun buildOutputCleanup<_dot_gradle<project_>>.div(a: buildOutputCleanup_dot_lock.Companion) = buildOutputCleanup_dot_lock<buildOutputCleanup<_dot_gradle<project_>>>(path)
@JvmName("22") operator fun _dot_gradle<project_>.div(a: vcsWorkingDirs.Companion) = vcsWorkingDirs<_dot_gradle<project_>>(path)
@JvmName("23") operator fun vcsWorkingDirs<_dot_gradle<project_>>.div(a: gc_dot_properties.Companion) = gc_dot_properties<vcsWorkingDirs<_dot_gradle<project_>>>(path)
@JvmName("24") operator fun src<project_>.div(a: main.Companion) = main<src<project_>>(path)
@JvmName("25") operator fun main<src<project_>>.div(a: java.Companion) = java<main<src<project_>>>(path)
@JvmName("26") operator fun main<src<project_>>.div(a: kotlin.Companion) = kotlin<main<src<project_>>>(path)
@JvmName("27") operator fun src<project_>.div(a: test.Companion) = test<src<project_>>(path)
@JvmName("28") operator fun test<src<project_>>.div(a: kotlin.Companion) = kotlin<test<src<project_>>>(path)
@JvmName("29") operator fun _dot_idea<project_>.div(a: workspace_dot_xml.Companion) = workspace_dot_xml<_dot_idea<project_>>(path)
@JvmName("30") operator fun _dot_idea<project_>.div(a: gradle_dot_xml.Companion) = gradle_dot_xml<_dot_idea<project_>>(path)
@JvmName("31") operator fun _dot_idea<project_>.div(a: kotlinc_dot_xml.Companion) = kotlinc_dot_xml<_dot_idea<project_>>(path)
@JvmName("32") operator fun _dot_idea<project_>.div(a: vcs_dot_xml.Companion) = vcs_dot_xml<_dot_idea<project_>>(path)
@JvmName("33") operator fun _dot_idea<project_>.div(a: markdown_dash_navigator.Companion) = markdown_dash_navigator<_dot_idea<project_>>(path)
@JvmName("34") operator fun markdown_dash_navigator<_dot_idea<project_>>.div(a: profiles_settings_dot_xml.Companion) = profiles_settings_dot_xml<markdown_dash_navigator<_dot_idea<project_>>>(path)
@JvmName("35") operator fun _dot_idea<project_>.div(a: markdown_dash_navigator_dot_xml.Companion) = markdown_dash_navigator_dot_xml<_dot_idea<project_>>(path)
@JvmName("36") operator fun _dot_idea<project_>.div(a: modules.Companion) = modules<_dot_idea<project_>>(path)
@JvmName("37") operator fun modules<_dot_idea<project_>>.div(a: yuri_test_dot_iml.Companion) = yuri_test_dot_iml<modules<_dot_idea<project_>>>(path)
@JvmName("38") operator fun modules<_dot_idea<project_>>.div(a: yuri_main_dot_iml.Companion) = yuri_main_dot_iml<modules<_dot_idea<project_>>>(path)
@JvmName("39") operator fun _dot_idea<project_>.div(a: kotlinScripting_dot_xml.Companion) = kotlinScripting_dot_xml<_dot_idea<project_>>(path)
@JvmName("40") operator fun _dot_idea<project_>.div(a: misc_dot_xml.Companion) = misc_dot_xml<_dot_idea<project_>>(path)
@JvmName("41") operator fun _dot_idea<project_>.div(a: uiDesigner_dot_xml.Companion) = uiDesigner_dot_xml<_dot_idea<project_>>(path)
@JvmName("42") operator fun gradle<project_>.div(a: wrapper.Companion) = wrapper<gradle<project_>>(path)
@JvmName("43") operator fun wrapper<gradle<project_>>.div(a: gradle_dash_wrapper_dot_properties.Companion) = gradle_dash_wrapper_dot_properties<wrapper<gradle<project_>>>(path)
@JvmName("44") operator fun wrapper<gradle<project_>>.div(a: gradle_dash_wrapper_dot_jar.Companion) = gradle_dash_wrapper_dot_jar<wrapper<gradle<project_>>>(path)
