
// This file was generated by Yuri, a type-safe URI builder for Kotlin.
package main.kotlin

import main.kotlin.G.*

abstract class GFile<T>( path: String ) {
  open val path: String = "$path/${javaClass.simpleName}"
  override fun toString() = path
}

open class G private constructor() {
  open class project_ {

@JvmName("_dot_") operator fun div(a: _dot_.Companion) = _dot_<project_>("/")

@JvmName("settings_dot_gradle") operator fun div(a: settings_dot_gradle.Companion) = settings_dot_gradle<project_>("/")

@JvmName("build_dot_gradle_dot_kts") operator fun div(a: build_dot_gradle_dot_kts.Companion) = build_dot_gradle_dot_kts<project_>("/")

@JvmName("_dot_gradle") operator fun div(a: _dot_gradle.Companion) = _dot_gradle<project_>("/")

@JvmName("README_dot_md") operator fun div(a: README_dot_md.Companion) = README_dot_md<project_>("/")

@JvmName("gradlew_dot_bat") operator fun div(a: gradlew_dot_bat.Companion) = gradlew_dot_bat<project_>("/")

@JvmName("src") operator fun div(a: src.Companion) = src<project_>("/")

@JvmName("gradlew") operator fun div(a: gradlew.Companion) = gradlew<project_>("/")

@JvmName("gradle") operator fun div(a: gradle.Companion) = gradle<project_>("/")

    companion object: project_()
  }


open class _dot_<T>(path: String): GFile<T>(path) { companion object }

open class settings_dot_gradle<T>(path: String): GFile<T>(path) { companion object }

open class build_dot_gradle_dot_kts<T>(path: String): GFile<T>(path) { companion object }

open class _dot_gradle<T>(path: String): GFile<T>(path) { companion object }

open class vcsWorkingDirs<T>(path: String): GFile<T>(path) { companion object }

open class README_dot_md<T>(path: String): GFile<T>(path) { companion object }

open class gradlew_dot_bat<T>(path: String): GFile<T>(path) { companion object }

open class src<T>(path: String): GFile<T>(path) { companion object }

open class main<T>(path: String): GFile<T>(path) { companion object }

open class java<T>(path: String): GFile<T>(path) { companion object }

open class J_dot_java<T>(path: String): GFile<T>(path) { companion object }

open class kotlin<T>(path: String): GFile<T>(path) { companion object }

open class HelloYuri_dot_kt<T>(path: String): GFile<T>(path) { companion object }

open class G_dot_kt<T>(path: String): GFile<T>(path) { companion object }

open class Y_dot_kt<T>(path: String): GFile<T>(path) { companion object }

open class co<T>(path: String): GFile<T>(path) { companion object }

open class ndan<T>(path: String): GFile<T>(path) { companion object }

open class yuri<T>(path: String): GFile<T>(path) { companion object }

open class Yuri_dot_kt<T>(path: String): GFile<T>(path) { companion object }

open class gradlew<T>(path: String): GFile<T>(path) { companion object }

open class gradle<T>(path: String): GFile<T>(path) { companion object }

open class wrapper<T>(path: String): GFile<T>(path) { companion object }

open class gradle_dash_wrapper_dot_properties<T>(path: String): GFile<T>(path) { companion object }

open class gradle_dash_wrapper_dot_jar<T>(path: String): GFile<T>(path) { companion object }

  companion object {
    fun uri(path: Any) = println(path)
  }
}
@JvmName("2") operator fun _dot_gradle<project_>.div(a: vcsWorkingDirs.Companion) = vcsWorkingDirs<_dot_gradle<project_>>(path)
@JvmName("3") operator fun src<project_>.div(a: main.Companion) = main<src<project_>>(path)
@JvmName("4") operator fun main<src<project_>>.div(a: java.Companion) = java<main<src<project_>>>(path)
@JvmName("5") operator fun java<main<src<project_>>>.div(a: J_dot_java.Companion) = J_dot_java<java<main<src<project_>>>>(path)
@JvmName("6") operator fun main<src<project_>>.div(a: kotlin.Companion) = kotlin<main<src<project_>>>(path)
@JvmName("7") operator fun kotlin<main<src<project_>>>.div(a: HelloYuri_dot_kt.Companion) = HelloYuri_dot_kt<kotlin<main<src<project_>>>>(path)
@JvmName("8") operator fun kotlin<main<src<project_>>>.div(a: G_dot_kt.Companion) = G_dot_kt<kotlin<main<src<project_>>>>(path)
@JvmName("9") operator fun kotlin<main<src<project_>>>.div(a: Y_dot_kt.Companion) = Y_dot_kt<kotlin<main<src<project_>>>>(path)
@JvmName("10") operator fun kotlin<main<src<project_>>>.div(a: co.Companion) = co<kotlin<main<src<project_>>>>(path)
@JvmName("11") operator fun co<kotlin<main<src<project_>>>>.div(a: ndan.Companion) = ndan<co<kotlin<main<src<project_>>>>>(path)
@JvmName("12") operator fun ndan<co<kotlin<main<src<project_>>>>>.div(a: yuri.Companion) = yuri<ndan<co<kotlin<main<src<project_>>>>>>(path)
@JvmName("13") operator fun yuri<ndan<co<kotlin<main<src<project_>>>>>>.div(a: Yuri_dot_kt.Companion) = Yuri_dot_kt<yuri<ndan<co<kotlin<main<src<project_>>>>>>>(path)
@JvmName("14") operator fun gradle<project_>.div(a: wrapper.Companion) = wrapper<gradle<project_>>(path)
@JvmName("15") operator fun wrapper<gradle<project_>>.div(a: gradle_dash_wrapper_dot_properties.Companion) = gradle_dash_wrapper_dot_properties<wrapper<gradle<project_>>>(path)
@JvmName("16") operator fun wrapper<gradle<project_>>.div(a: gradle_dash_wrapper_dot_jar.Companion) = gradle_dash_wrapper_dot_jar<wrapper<gradle<project_>>>(path)
