// This file was generated by Yuri, a type-safe URI builder for Kotlin.
package main.kotlin

import main.kotlin.G.*

abstract class GFile<T>

open class G private constructor() {
  open class project_ {

@JvmName("_dot_") operator fun div(a: _dot_.Companion) = _dot_<project_>()

@JvmName("settings_dot_gradle") operator fun div(a: settings_dot_gradle.Companion) = settings_dot_gradle<project_>()

@JvmName("build") operator fun div(a: build.Companion) = build<project_>()

@JvmName("build_dot_gradle_dot_kts") operator fun div(a: build_dot_gradle_dot_kts.Companion) = build_dot_gradle_dot_kts<project_>()

@JvmName("_dot_gradle") operator fun div(a: _dot_gradle.Companion) = _dot_gradle<project_>()

@JvmName("README_dot_md") operator fun div(a: README_dot_md.Companion) = README_dot_md<project_>()

@JvmName("gradlew_dot_bat") operator fun div(a: gradlew_dot_bat.Companion) = gradlew_dot_bat<project_>()

@JvmName("src") operator fun div(a: src.Companion) = src<project_>()

@JvmName("_dot_idea") operator fun div(a: _dot_idea.Companion) = _dot_idea<project_>()

@JvmName("gradlew") operator fun div(a: gradlew.Companion) = gradlew<project_>()

@JvmName("gradle") operator fun div(a: gradle.Companion) = gradle<project_>()

    companion object: project_()
  }


open class _dot_<T>: GFile<T>() { companion object }

open class settings_dot_gradle<T>: GFile<T>() { companion object }

open class build<T>: GFile<T>() { companion object }

open class generated<T>: GFile<T>() { companion object }

open class source<T>: GFile<T>() { companion object }

open class yuri<T>: GFile<T>() { companion object }

open class main<T>: GFile<T>() { companion object }

open class G_dot_kt<T>: GFile<T>() { companion object }

open class classes<T>: GFile<T>() { companion object }

open class kotlin<T>: GFile<T>() { companion object }

open class sessions<T>: GFile<T>() { companion object }

open class compileKotlin<T>: GFile<T>() { companion object }

open class build_dash_history_dot_bin<T>: GFile<T>() { companion object }

open class caches_dash_jvm<T>: GFile<T>() { companion object }

open class inputs<T>: GFile<T>() { companion object }

open class jvm<T>: GFile<T>() { companion object }

open class lookups<T>: GFile<T>() { companion object }

open class dirty_dash_sources_dot_txt<T>: GFile<T>() { companion object }

open class build_dot_gradle_dot_kts<T>: GFile<T>() { companion object }

open class _dot_gradle<T>: GFile<T>() { companion object }

open class buildOutputCleanup<T>: GFile<T>() { companion object }

open class outputFiles_dot_bin<T>: GFile<T>() { companion object }

open class cache_dot_properties<T>: GFile<T>() { companion object }

open class buildOutputCleanup_dot_lock<T>: GFile<T>() { companion object }

open class vcsWorkingDirs<T>: GFile<T>() { companion object }

open class gc_dot_properties<T>: GFile<T>() { companion object }

open class README_dot_md<T>: GFile<T>() { companion object }

open class gradlew_dot_bat<T>: GFile<T>() { companion object }

open class src<T>: GFile<T>() { companion object }

open class java<T>: GFile<T>() { companion object }

open class J_dot_java<T>: GFile<T>() { companion object }

open class Main_dot_kt<T>: GFile<T>() { companion object }

open class Y_dot_kt<T>: GFile<T>() { companion object }

open class test<T>: GFile<T>() { companion object }

open class _dot_idea<T>: GFile<T>() { companion object }

open class workspace_dot_xml<T>: GFile<T>() { companion object }

open class gradle_dot_xml<T>: GFile<T>() { companion object }

open class kotlinc_dot_xml<T>: GFile<T>() { companion object }

open class vcs_dot_xml<T>: GFile<T>() { companion object }

open class markdown_dash_navigator<T>: GFile<T>() { companion object }

open class profiles_settings_dot_xml<T>: GFile<T>() { companion object }

open class markdown_dash_navigator_dot_xml<T>: GFile<T>() { companion object }

open class modules<T>: GFile<T>() { companion object }

open class yuri_test_dot_iml<T>: GFile<T>() { companion object }

open class yuri_main_dot_iml<T>: GFile<T>() { companion object }

open class kotlinScripting_dot_xml<T>: GFile<T>() { companion object }

open class misc_dot_xml<T>: GFile<T>() { companion object }

open class gradlew<T>: GFile<T>() { companion object }

open class gradle<T>: GFile<T>() { companion object }

open class wrapper<T>: GFile<T>() { companion object }

open class gradle_dash_wrapper_dot_properties<T>: GFile<T>() { companion object }

open class gradle_dash_wrapper_dot_jar<T>: GFile<T>() { companion object }

  companion object {
    fun uri(path: Any) = println(path)
  }
}
operator fun build<project_>.div(a: generated.Companion) = generated<build<project_>>()
operator fun generated<build<project_>>.div(a: source.Companion) = source<generated<build<project_>>>()
operator fun source<generated<build<project_>>>.div(a: yuri.Companion) = yuri<source<generated<build<project_>>>>()
operator fun yuri<source<generated<build<project_>>>>.div(a: main.Companion) = main<yuri<source<generated<build<project_>>>>>()
operator fun main<yuri<source<generated<build<project_>>>>>.div(a: G_dot_kt.Companion) = G_dot_kt<main<yuri<source<generated<build<project_>>>>>>()
operator fun build<project_>.div(a: classes.Companion) = classes<build<project_>>()
operator fun classes<build<project_>>.div(a: kotlin.Companion) = kotlin<classes<build<project_>>>()
operator fun build<project_>.div(a: kotlin.Companion) = kotlin<build<project_>>()
operator fun kotlin<build<project_>>.div(a: sessions.Companion) = sessions<kotlin<build<project_>>>()
operator fun kotlin<build<project_>>.div(a: compileKotlin.Companion) = compileKotlin<kotlin<build<project_>>>()
operator fun compileKotlin<kotlin<build<project_>>>.div(a: build_dash_history_dot_bin.Companion) = build_dash_history_dot_bin<compileKotlin<kotlin<build<project_>>>>()
operator fun compileKotlin<kotlin<build<project_>>>.div(a: caches_dash_jvm.Companion) = caches_dash_jvm<compileKotlin<kotlin<build<project_>>>>()
operator fun caches_dash_jvm<compileKotlin<kotlin<build<project_>>>>.div(a: inputs.Companion) = inputs<caches_dash_jvm<compileKotlin<kotlin<build<project_>>>>>()
operator fun caches_dash_jvm<compileKotlin<kotlin<build<project_>>>>.div(a: jvm.Companion) = jvm<caches_dash_jvm<compileKotlin<kotlin<build<project_>>>>>()
operator fun caches_dash_jvm<compileKotlin<kotlin<build<project_>>>>.div(a: lookups.Companion) = lookups<caches_dash_jvm<compileKotlin<kotlin<build<project_>>>>>()
operator fun compileKotlin<kotlin<build<project_>>>.div(a: dirty_dash_sources_dot_txt.Companion) = dirty_dash_sources_dot_txt<compileKotlin<kotlin<build<project_>>>>()
operator fun _dot_gradle<project_>.div(a: buildOutputCleanup.Companion) = buildOutputCleanup<_dot_gradle<project_>>()
operator fun buildOutputCleanup<_dot_gradle<project_>>.div(a: outputFiles_dot_bin.Companion) = outputFiles_dot_bin<buildOutputCleanup<_dot_gradle<project_>>>()
operator fun buildOutputCleanup<_dot_gradle<project_>>.div(a: cache_dot_properties.Companion) = cache_dot_properties<buildOutputCleanup<_dot_gradle<project_>>>()
operator fun buildOutputCleanup<_dot_gradle<project_>>.div(a: buildOutputCleanup_dot_lock.Companion) = buildOutputCleanup_dot_lock<buildOutputCleanup<_dot_gradle<project_>>>()
operator fun _dot_gradle<project_>.div(a: vcsWorkingDirs.Companion) = vcsWorkingDirs<_dot_gradle<project_>>()
operator fun vcsWorkingDirs<_dot_gradle<project_>>.div(a: gc_dot_properties.Companion) = gc_dot_properties<vcsWorkingDirs<_dot_gradle<project_>>>()
operator fun src<project_>.div(a: main.Companion) = main<src<project_>>()
operator fun main<src<project_>>.div(a: java.Companion) = java<main<src<project_>>>()
operator fun java<main<src<project_>>>.div(a: J_dot_java.Companion) = J_dot_java<java<main<src<project_>>>>()
operator fun main<src<project_>>.div(a: kotlin.Companion) = kotlin<main<src<project_>>>()
operator fun kotlin<main<src<project_>>>.div(a: G_dot_kt.Companion) = G_dot_kt<kotlin<main<src<project_>>>>()
operator fun kotlin<main<src<project_>>>.div(a: Main_dot_kt.Companion) = Main_dot_kt<kotlin<main<src<project_>>>>()
operator fun kotlin<main<src<project_>>>.div(a: Y_dot_kt.Companion) = Y_dot_kt<kotlin<main<src<project_>>>>()
operator fun src<project_>.div(a: test.Companion) = test<src<project_>>()
operator fun test<src<project_>>.div(a: kotlin.Companion) = kotlin<test<src<project_>>>()
operator fun _dot_idea<project_>.div(a: workspace_dot_xml.Companion) = workspace_dot_xml<_dot_idea<project_>>()
operator fun _dot_idea<project_>.div(a: gradle_dot_xml.Companion) = gradle_dot_xml<_dot_idea<project_>>()
operator fun _dot_idea<project_>.div(a: kotlinc_dot_xml.Companion) = kotlinc_dot_xml<_dot_idea<project_>>()
operator fun _dot_idea<project_>.div(a: vcs_dot_xml.Companion) = vcs_dot_xml<_dot_idea<project_>>()
operator fun _dot_idea<project_>.div(a: markdown_dash_navigator.Companion) = markdown_dash_navigator<_dot_idea<project_>>()
operator fun markdown_dash_navigator<_dot_idea<project_>>.div(a: profiles_settings_dot_xml.Companion) = profiles_settings_dot_xml<markdown_dash_navigator<_dot_idea<project_>>>()
operator fun _dot_idea<project_>.div(a: markdown_dash_navigator_dot_xml.Companion) = markdown_dash_navigator_dot_xml<_dot_idea<project_>>()
operator fun _dot_idea<project_>.div(a: modules.Companion) = modules<_dot_idea<project_>>()
operator fun modules<_dot_idea<project_>>.div(a: yuri_test_dot_iml.Companion) = yuri_test_dot_iml<modules<_dot_idea<project_>>>()
operator fun modules<_dot_idea<project_>>.div(a: yuri_main_dot_iml.Companion) = yuri_main_dot_iml<modules<_dot_idea<project_>>>()
operator fun _dot_idea<project_>.div(a: kotlinScripting_dot_xml.Companion) = kotlinScripting_dot_xml<_dot_idea<project_>>()
operator fun _dot_idea<project_>.div(a: misc_dot_xml.Companion) = misc_dot_xml<_dot_idea<project_>>()
operator fun gradle<project_>.div(a: wrapper.Companion) = wrapper<gradle<project_>>()
operator fun wrapper<gradle<project_>>.div(a: gradle_dash_wrapper_dot_properties.Companion) = gradle_dash_wrapper_dot_properties<wrapper<gradle<project_>>>()
operator fun wrapper<gradle<project_>>.div(a: gradle_dash_wrapper_dot_jar.Companion) = gradle_dash_wrapper_dot_jar<wrapper<gradle<project_>>>()
