name: CI

on:
  push:
    paths:
    - '**.kt'
    - '**.kts'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 13
        uses: actions/setup-java@v2
        with:
          java-version: 13
      - name: Build with Gradle
        run: ./gradlew consumer --stacktrace
